name: ethereum-returns-feature-pipeline

on: push
  # schedule:
  #   - cron: '0 * * * *'
  # workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # - name: Install Chrome and Chromedriver
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y chromium-browser
    #     CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1)
    #     CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
    #     wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
    #     unzip chromedriver_linux64.zip
    #     sudo mv chromedriver /usr/local/bin/
    #     sudo chmod +x /usr/local/bin/chromedriver
        
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
    - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_feature_pipeline.txt

    - name: Execute Python workflows from bash script
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: jupyter nbconvert --to notebook --execute notebooks/04_feature_pipeline.ipynb
